! Generated by fortsym. Do not edit.
! Generator: tools/gc_symbolics/app/gen_manufactured_torus.f90
! Generator revision: fortsym@77b031204c76fa88872ddface3af6ac3a25fbb00
! Regenerate with: cd tools/gc_symbolics && fo exec gen_manufactured_torus ../../test/generated_manufactured_torus.f90

module manufactured_torus_kernel
    implicit none
    private
    public :: evaluate_manufactured_torus
contains

    pure subroutine evaluate_manufactured_torus(radius, phi, theta, major_radius, toroidal_flux, q_axis, &
            shear_shape, bmod, sqrtg, grad_log_b_1, grad_log_b_2, grad_log_b_3, h_cov_1, h_cov_2, h_cov_3, &
            h_con_1, h_con_2, h_con_3, curl_h_1, curl_h_2, curl_h_3, psi, grad_psi_1, grad_psi_2, grad_psi_3, &
            q_safety, magnetic_shear)
        use, intrinsic :: iso_fortran_env, only: dp => real64
        implicit none
        real(dp), intent(in) :: radius, phi, theta, major_radius, toroidal_flux, q_axis, shear_shape
        real(dp), intent(out) :: bmod, sqrtg, grad_log_b_1, grad_log_b_2, grad_log_b_3, h_cov_1, &
            h_cov_2, h_cov_3, h_con_1, h_con_2, h_con_3, curl_h_1, curl_h_2, curl_h_3, psi, grad_psi_1, &
            grad_psi_2, grad_psi_3, q_safety, magnetic_shear
        real(dp) :: t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12

        t1 = toroidal_flux**2
        t2 = radius**2
        t3 = shear_shape*t2/major_radius**2 + 1
        t4 = t3**2
        t5 = sqrt(t1 + t2*t1*t4/major_radius**2/q_axis**2)
        t6 = cos(theta)
        t7 = major_radius + radius*t6
        t8 = shear_shape*toroidal_flux*t2*2/major_radius**3/q_axis + toroidal_flux*t3/major_radius/ &
            q_axis
        t9 = sin(theta)
        t10 = radius**3
        t11 = major_radius**2
        t12 = sqrt(t11 - t2)
        bmod = t5/t7
        sqrtg = radius*t7
        grad_log_b_1 = t7*(radius*toroidal_flux*t8*t3/major_radius/q_axis/t5/t7 - t6*t5/t7**2)/t5
        grad_log_b_2 = 0
        grad_log_b_3 = radius*t9/t7
        h_cov_1 = 0
        h_cov_2 = toroidal_flux*t7/t5
        h_cov_3 = toroidal_flux*t2*t3/major_radius/q_axis/t5
        h_con_1 = 0
        h_con_2 = toroidal_flux/t5/t7
        h_con_3 = toroidal_flux*t3/major_radius/q_axis/t5
        curl_h_1 = toroidal_flux*t9/t5/t7
        curl_h_2 = -(radius*toroidal_flux*t3*2/major_radius/q_axis/t5 + shear_shape*toroidal_flux*t10*2/ &
            major_radius**3/q_axis/t5 - t10*t1*t4*t8/major_radius**2/q_axis**2/t5**3)/radius/t7
        curl_h_3 = (-radius*t1*t7*t8*t3/major_radius/q_axis/t5**3 + toroidal_flux*t6/t5)/radius/t7
        psi = toroidal_flux*(shear_shape*radius**4*1.0_dp/4.0_dp/major_radius**2 + t2*1.0_dp/2.0_dp)/ &
            major_radius/q_axis
        grad_psi_1 = toroidal_flux*(radius + shear_shape*t10/major_radius**2)/major_radius/q_axis
        grad_psi_2 = 0
        grad_psi_3 = 0
        q_safety = major_radius*q_axis/t12/t3
        magnetic_shear = radius*t12*(major_radius*q_axis/radius/t12/t3 - t11*q_axis**2*(shear_shape* &
            toroidal_flux*t12*t2*2/major_radius**3/q_axis + toroidal_flux*t12*t3/major_radius/q_axis - &
            toroidal_flux*t2*t3/major_radius/q_axis/t12)/radius/toroidal_flux/t12**2/t3**2)*t3/major_radius/ &
            q_axis

    end subroutine evaluate_manufactured_torus

end module manufactured_torus_kernel

