! Generated by fortsym. Do not edit.
! Generator: tools/gc_symbolics/app/gen_circular_torus_volume.f90
! Generator revision: fortsym@77b031204c76fa88872ddface3af6ac3a25fbb00
! Regenerate with: cd tools/gc_symbolics && fo exec gen_circular_torus_volume ../../test/generated_circular_torus_volume.f90

module circular_torus_volume_kernel
    implicit none
    private
    public :: evaluate_circular_torus_dvds
contains

    pure subroutine evaluate_circular_torus_dvds(s_tor, major_radius, minor_radius, dVds)
        use, intrinsic :: iso_fortran_env, only: dp => real64
        implicit none
        real(dp), intent(in) :: s_tor, major_radius, minor_radius
        real(dp), intent(out) :: dVds
        real(dp) :: t1

        t1 = major_radius - sqrt(major_radius**2 - minor_radius**2)
        dVds = major_radius*3.1415926535897931E+000_dp**2*(major_radius - s_tor*t1)*t1*4

    end subroutine evaluate_circular_torus_dvds

end module circular_torus_volume_kernel
