module neort_gc_eqdsk_cut_jet
    !! Exact Buchholz Eq. 13 event/rate provider for the direct EQDSK chart.
    !!
    !! Handwritten code owns only validated cell selection and the physical
    !! branch choice for F outside the separatrix.  Tensor-quintic evaluation,
    !! all derivatives, F-profile normalization, C, grad(C), and Cdot are
    !! generated by Fortsym.
    use, intrinsic :: ieee_arithmetic, only: ieee_is_finite
    use, intrinsic :: iso_fortran_env, only: dp => real64
    use field_eq_mod, only: btf, hfpol, icp, ipoint, nrad, nzet, rad, zet, &
        hrad, hzet, psi_sep, rtf, splfpol, splpsi, use_fpol
    use neort_eqdsk_cut_numerator_symbolic, only: &
        evaluate_neort_eqdsk_cut_numerator
    use neort_eqdsk_cut_numerator_hessian_symbolic, only: &
        evaluate_neort_eqdsk_cut_numerator_hessian
    use neort_eqdsk_cut_jet_symbolic, only: evaluate_neort_eqdsk_cut_jet
    use neort_eqdsk_quintic_cell_jet_symbolic, only: &
        evaluate_neort_eqdsk_quintic_cell_jet
    use neort_eqdsk_quintic_cell_fourth_jet_symbolic, only: &
        evaluate_neort_eqdsk_quintic_cell_fourth_jet
    use neort_eqdsk_quintic_profile_jet_symbolic, only: &
        evaluate_neort_eqdsk_quintic_profile_jet
    implicit none
    private

    integer, parameter, public :: EQDSK_CUT_JET_SUCCESS = 0
    integer, parameter, public :: EQDSK_CUT_JET_INVALID_INPUT = 1
    integer, parameter, public :: EQDSK_CUT_JET_UNINITIALIZED = 2
    integer, parameter, public :: EQDSK_CUT_JET_OUT_OF_DOMAIN = 3
    integer, parameter, public :: EQDSK_CUT_JET_NONFINITE = 4

    type, public :: eqdsk_cut_jet_t
        !! psi_jet and F_jet are unscaled equilibrium quantities.  The cut
        !! quantities include field_scale exactly as certified by the generated
        !! field_scale**2 identity.
        !! psi_jet ordering is psi, first derivatives, symmetric second,
        !! symmetric third, then symmetric fourth derivatives.
        real(dp) :: psi_jet(15) = 0.0_dp
        real(dp) :: f_jet(3) = 0.0_dp
        real(dp) :: cut_value = 0.0_dp
        real(dp) :: d_cut_d_R = 0.0_dp
        real(dp) :: d_cut_d_arc_phi = 0.0_dp
        real(dp) :: d_cut_d_Z = 0.0_dp
        real(dp) :: cut_rate = 0.0_dp
        real(dp) :: absolute_cut_rate = 0.0_dp
        real(dp) :: orientation_scalar = 0.0_dp
        real(dp) :: cut_numerator = 0.0_dp
        real(dp) :: d_cut_numerator_d_R = 0.0_dp
        real(dp) :: d_cut_numerator_d_Z = 0.0_dp
        real(dp) :: d2_cut_numerator_d_R2 = 0.0_dp
        real(dp) :: d2_cut_numerator_d_RdZ = 0.0_dp
        real(dp) :: d2_cut_numerator_d_Z2 = 0.0_dp
    end type eqdsk_cut_jet_t

    public :: evaluate_eqdsk_cut_jet

contains

    subroutine evaluate_eqdsk_cut_jet(position, field_scale, cut_orientation, &
            coordinate_velocity, result, status)
        real(dp), intent(in) :: position(3), field_scale
        integer, intent(in) :: cut_orientation
        real(dp), intent(in) :: coordinate_velocity(3)
        type(eqdsk_cut_jet_t), intent(out) :: result
        integer, intent(out) :: status

        real(dp) :: coefficient(6,6), profile_coefficient(0:5)
        real(dp) :: delta_R, delta_Z, profile_delta, psi_hat
        real(dp) :: profile_value, profile_first, profile_second, vacuum_f
        integer :: cell_R, cell_Z, cell_pointer, profile_cell

        result = eqdsk_cut_jet_t()
        status = EQDSK_CUT_JET_INVALID_INPUT
        if (.not. all(ieee_is_finite([position, field_scale, &
                coordinate_velocity]))) return
        if (position(1) <= 0.0_dp .or. field_scale <= 0.0_dp) return
        if (abs(cut_orientation) /= 1) return
        status = EQDSK_CUT_JET_UNINITIALIZED
        if (nrad < 2 .or. nzet < 2 .or. icp < 1) return
        if (.not. allocated(rad) .or. .not. allocated(zet)) return
        if (.not. allocated(splpsi) .or. .not. allocated(ipoint)) return
        if (size(rad) /= nrad .or. size(zet) /= nzet) return
        if (size(splpsi,1) /= 6 .or. size(splpsi,2) /= 6) return
        if (size(splpsi,3) < icp) return
        if (size(ipoint,1) /= nrad .or. size(ipoint,2) /= nzet) return
        if (.not. all(ieee_is_finite([rad, zet, hrad, hzet, psi_sep, &
                btf, rtf]))) return
        if (hrad <= 0.0_dp .or. hzet <= 0.0_dp) return
        ! Profile cells are ordered in psi_hat=psi/psi_sep from zero to one.
        ! A negative separatrix flux would reverse that coordinate without
        ! reversing the spline ownership rules, so it is not this contract.
        if (psi_sep <= tiny(1.0_dp)) return
        if (position(1) < rad(1) .or. position(1) > rad(nrad) .or. &
                position(2) < zet(1) .or. position(2) > zet(nzet)) then
            status = EQDSK_CUT_JET_OUT_OF_DOMAIN
            return
        end if

        cell_R = min(nrad, max(1, int((position(1)-rad(1))/hrad)+1))
        cell_Z = min(nzet, max(1, int((position(2)-zet(1))/hzet)+1))
        cell_pointer = ipoint(cell_R, cell_Z)
        if (cell_pointer < 1 .or. cell_pointer > size(splpsi,3)) return
        coefficient = splpsi(:,:,cell_pointer)
        if (.not. all(ieee_is_finite(coefficient))) then
            status = EQDSK_CUT_JET_NONFINITE
            return
        end if
        delta_R = position(1)-rad(cell_R)
        delta_Z = position(2)-zet(cell_Z)
        call evaluate_neort_eqdsk_quintic_cell_jet(delta_R, delta_Z, &
            coefficient(1,1), coefficient(1,2), coefficient(1,3), &
            coefficient(1,4), coefficient(1,5), coefficient(1,6), &
            coefficient(2,1), coefficient(2,2), coefficient(2,3), &
            coefficient(2,4), coefficient(2,5), coefficient(2,6), &
            coefficient(3,1), coefficient(3,2), coefficient(3,3), &
            coefficient(3,4), coefficient(3,5), coefficient(3,6), &
            coefficient(4,1), coefficient(4,2), coefficient(4,3), &
            coefficient(4,4), coefficient(4,5), coefficient(4,6), &
            coefficient(5,1), coefficient(5,2), coefficient(5,3), &
            coefficient(5,4), coefficient(5,5), coefficient(5,6), &
            coefficient(6,1), coefficient(6,2), coefficient(6,3), &
            coefficient(6,4), coefficient(6,5), coefficient(6,6), &
            result%psi_jet(1), result%psi_jet(2), result%psi_jet(3), &
            result%psi_jet(4), result%psi_jet(5), result%psi_jet(6), &
            result%psi_jet(7), result%psi_jet(8), result%psi_jet(9), &
            result%psi_jet(10))
        call evaluate_neort_eqdsk_quintic_cell_fourth_jet(delta_R, delta_Z, &
            coefficient(1,1), coefficient(1,2), coefficient(1,3), &
            coefficient(1,4), coefficient(1,5), coefficient(1,6), &
            coefficient(2,1), coefficient(2,2), coefficient(2,3), &
            coefficient(2,4), coefficient(2,5), coefficient(2,6), &
            coefficient(3,1), coefficient(3,2), coefficient(3,3), &
            coefficient(3,4), coefficient(3,5), coefficient(3,6), &
            coefficient(4,1), coefficient(4,2), coefficient(4,3), &
            coefficient(4,4), coefficient(4,5), coefficient(4,6), &
            coefficient(5,1), coefficient(5,2), coefficient(5,3), &
            coefficient(5,4), coefficient(5,5), coefficient(5,6), &
            coefficient(6,1), coefficient(6,2), coefficient(6,3), &
            coefficient(6,4), coefficient(6,5), coefficient(6,6), &
            result%psi_jet(11), result%psi_jet(12), result%psi_jet(13), &
            result%psi_jet(14), result%psi_jet(15))
        if (.not. all(ieee_is_finite(result%psi_jet))) then
            status = EQDSK_CUT_JET_NONFINITE
            return
        end if

        profile_coefficient = 0.0_dp
        profile_delta = 0.0_dp
        if (use_fpol) then
            if (.not. allocated(splfpol)) return
            if (size(splfpol,1) < 6 .or. size(splfpol,2) < nrad) return
            if (.not. ieee_is_finite(hfpol) .or. hfpol <= 0.0_dp) return
            psi_hat = result%psi_jet(1)/psi_sep
            if (.not. ieee_is_finite(psi_hat)) then
                status = EQDSK_CUT_JET_NONFINITE
                return
            end if
            if (psi_hat > 1.0_dp) then
                result%f_jet = [splfpol(0,nrad), 0.0_dp, 0.0_dp]
            else
                profile_cell = min(nrad, &
                    max(1, max(0, int(psi_hat/hfpol))+1))
                profile_delta = psi_hat-real(profile_cell-1,dp)*hfpol
                profile_coefficient = splfpol(0:5,profile_cell)
                call evaluate_neort_eqdsk_quintic_profile_jet(profile_delta, &
                    profile_coefficient(0), profile_coefficient(1), &
                    profile_coefficient(2), profile_coefficient(3), &
                    profile_coefficient(4), profile_coefficient(5), btf, rtf, &
                    profile_value, profile_first, profile_second, vacuum_f)
                result%f_jet = [profile_value, profile_first, profile_second]
            end if
        else
            call evaluate_neort_eqdsk_quintic_profile_jet(profile_delta, &
                profile_coefficient(0), profile_coefficient(1), &
                profile_coefficient(2), profile_coefficient(3), &
                profile_coefficient(4), profile_coefficient(5), btf, rtf, &
                profile_value, profile_first, profile_second, vacuum_f)
            result%f_jet = [vacuum_f, 0.0_dp, 0.0_dp]
        end if
        if (.not. all(ieee_is_finite(result%f_jet))) then
            status = EQDSK_CUT_JET_NONFINITE
            return
        end if

        call evaluate_neort_eqdsk_cut_numerator(position(1), &
            result%psi_jet(2), result%psi_jet(3), &
            result%psi_jet(4), result%psi_jet(5), result%psi_jet(6), &
            result%psi_jet(7), result%psi_jet(8), result%psi_jet(9), &
            result%psi_jet(10), result%f_jet(1), result%f_jet(2), psi_sep, &
            result%cut_numerator, result%d_cut_numerator_d_R, &
            result%d_cut_numerator_d_Z)
        call evaluate_neort_eqdsk_cut_numerator_hessian(position(1), &
            result%psi_jet(2), result%psi_jet(3), result%psi_jet(4), &
            result%psi_jet(5), result%psi_jet(6), result%psi_jet(7), &
            result%psi_jet(8), result%psi_jet(9), result%psi_jet(10), &
            result%psi_jet(11), result%psi_jet(12), result%psi_jet(13), &
            result%psi_jet(14), result%psi_jet(15), result%f_jet(1), &
            result%f_jet(2), result%f_jet(3), psi_sep, &
            result%d2_cut_numerator_d_R2, &
            result%d2_cut_numerator_d_RdZ, &
            result%d2_cut_numerator_d_Z2)
        if (.not. all(ieee_is_finite([result%cut_numerator, &
                result%d_cut_numerator_d_R, &
                result%d_cut_numerator_d_Z, &
                result%d2_cut_numerator_d_R2, &
                result%d2_cut_numerator_d_RdZ, &
                result%d2_cut_numerator_d_Z2]))) then
            result = eqdsk_cut_jet_t()
            status = EQDSK_CUT_JET_NONFINITE
            return
        end if

        call evaluate_neort_eqdsk_cut_jet(position(1), field_scale, &
            real(cut_orientation,dp), result%psi_jet(1), result%psi_jet(2), &
            result%psi_jet(3), result%psi_jet(4), result%psi_jet(5), &
            result%psi_jet(6), result%psi_jet(7), result%psi_jet(8), &
            result%psi_jet(9), result%psi_jet(10), result%f_jet(1), &
            result%f_jet(2), psi_sep, &
            coordinate_velocity(1), coordinate_velocity(3), &
            coordinate_velocity(2), result%cut_value, result%d_cut_d_R, &
            result%d_cut_d_arc_phi, result%d_cut_d_Z, result%cut_rate, &
            result%absolute_cut_rate, result%orientation_scalar)
        if (.not. all(ieee_is_finite([result%cut_value, result%d_cut_d_R, &
                result%d_cut_d_arc_phi, result%d_cut_d_Z, result%cut_rate, &
                result%absolute_cut_rate, result%orientation_scalar, &
                result%cut_numerator, result%d_cut_numerator_d_R, &
                result%d_cut_numerator_d_Z, &
                result%d2_cut_numerator_d_R2, &
                result%d2_cut_numerator_d_RdZ, &
                result%d2_cut_numerator_d_Z2]))) then
            result = eqdsk_cut_jet_t()
            status = EQDSK_CUT_JET_NONFINITE
            return
        end if
        status = EQDSK_CUT_JET_SUCCESS
    end subroutine evaluate_eqdsk_cut_jet

end module neort_gc_eqdsk_cut_jet
